kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.16
    commands:
      - echo "Waiting for Grafana to come up"
      - timeout=$(($(date +%s) + 10))
      - until [ "$(date +%s)" -gt "$timeout" ] || curl -s --fail http://grafana:3000; do sleep 5; done
      - make linux
      - cp conf/importer-example.yml conf/importer.yml
      - make test
      - ./bin/gdg_linux version
services:
  - name: grafana
    image: grafana/grafana:7.5.6-ubuntu

trigger:
  event:
    - push
    - pull_request
---
kind: pipeline
name: documentation

steps:
  - name: Submodule sync
    image: alpine/git
    commands:
      - "git submodule update --init"
  - name: build
    image: golang:1.16
    commands:
      - "cd documentation"
      - "rm -fr hugo"
      - "wget --continue https://github.com/gohugoio/hugo/releases/download/v0.84.0/hugo_extended_0.84.0_Linux-64bit.tar.gz"
      - "tar xvfz hugo_extended_0.84.0_Linux-64bit.tar.gz"
      - "./hugo --destination public --baseURL https://netsage-project.github.io/grafana-dashboard-manager/"
      - "ls -lh public"
  - name: publish
    image: plugins/gh-pages
    settings:
      pages_directory: documentation/public
      upstream_name: origin
      remote_url: https://github.com/netsage-project/grafana-dashboard-manager.git
      target_branch: gh-pages
      force_push: true
      delete: true
      username:
        from_secret: gh_username
      password:
        from_secret: gh_password
      when:
        branch: master
        event: push
---
kind: pipeline
name: release

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event: tag
  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: gh_secret
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

volumes:
  - name: deps
    temp: {}
