# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy


builds:
  - id: gdg
    env:
      - CGO_ENABLED=0
    binary: gdg
    ldflags: -s -w -X github.com/esnet/gdg/internal/version.GitCommit={{ .Commit }} -X github.com/esnet/gdg/internal/version.BuildDate={{ .Date }}  -X github.com/esnet/gdg/internal/version.Version={{ .Tag }}
    main: ./cmd/gdg
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - 386
      - amd64
  - id: gdg-generate
    env:
      - CGO_ENABLED=0
    binary: gdg-generate
    ldflags: -s -w -X github.com/esnet/gdg/internal/version.GitCommit={{ .Commit }} -X github.com/esnet/gdg/internal/version.BuildDate={{ .Date }}  -X github.com/esnet/gdg/internal/version.Version={{ .Tag }}
    main: ./cmd/gdg-generate
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - 386
      - amd64

nfpms:
  - id: gdg
    package_name: gdg
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://software.es.net/gdg/
    maintainer: GDG ESNet <gdg@es.net>
    description: |-
      GDG is a tool used to manage dashboards, connections, organizations and various entities of the Grafana application.
    license: BSD License
    ids:
      - gdg
      - gdg-generate
    formats:
      - apk
      - deb
      - rpm

    # Template to the path that the binaries should be installed.
    # Defaults to `/usr/bin`.
    bindir: /usr/bin

    # Section.
    section: default

    # Priority.
    priority: extra

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      # Simple config file
      - src: config/gdg-example.yml
        dst: /etc/gdg/gdg.yml
        type: config
      # Simple config file
      - src: config/templates-example.yml
        dst: /etc/gdg/templates.yml
        type: config


universal_binaries:
  - id: gdg
    name_template: gdg
    replace: true
    ids: [gdg]
  - id: gdg-generate
    name_template: gdg-generate
    replace: true
    ids: [gdg-generate]

release:
  prerelease: auto


dockers_v2:
  - id: gdg
    dockerfile: "Dockerfile"
    images:
      - "ghcr.io/esnet/gdg"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/386
    tags:
      - "{{ .Version }}"
      - "{{ .RawVersion }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Grafana Dash-n-Grab"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

homebrew_casks:
  - name: gdg
    homepage: https://software.es.net/gdg
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: Grafana Dash-n-Grab (GDG) -- Dashboard/DataSource Manager for grafana supporting backup/restore to local filesystem, s3, gcs, azure, and other S3 compatible storage engines.
    directory: Casks
    repository:
      owner: esnet
      name: homebrew-gdg
      token: "{{ .Env.HOMEBREW_TOKEN }}"
      branch: main
    commit_author:
      name: GDG ESNet
      email: gdg@es.net
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdg"]
          end

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    ids:
      - gdg
      - gdg-generate
    files:
      - README*
      - config/gdg-example.yml
      - config/templates-example.yml

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
