all: true
dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
pkgname: mocks
recursive: false
filename: "{{.InterfaceName}}.go"
template: testify
packages:
  github.com/esnet/gdg/internal/service:
    config:
      all: true
      dir: '{{.InterfaceDir}}/mocks'
      pkgname: mocks
