[[imports]]
path = "github.com/McShelby/hugo-theme-relearn"

## layouts
[[mounts]]
source = "layouts"
target = "layouts"

## assets
[[mounts]]
source = "assets"
target = "assets"

## static
[[mounts]]
source = "static"
target = "static"
