// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	filters "github.com/esnet/gdg/internal/service/filters"
	mock "github.com/stretchr/testify/mock"

	service "github.com/esnet/gdg/internal/service"
)

// DashboardPermissionsApi is an autogenerated mock type for the DashboardPermissionsApi type
type DashboardPermissionsApi struct {
	mock.Mock
}

type DashboardPermissionsApi_Expecter struct {
	mock *mock.Mock
}

func (_m *DashboardPermissionsApi) EXPECT() *DashboardPermissionsApi_Expecter {
	return &DashboardPermissionsApi_Expecter{mock: &_m.Mock}
}

// ClearDashboardPermissions provides a mock function with given fields: filterReq
func (_m *DashboardPermissionsApi) ClearDashboardPermissions(filterReq filters.Filter) error {
	ret := _m.Called(filterReq)

	if len(ret) == 0 {
		panic("no return value specified for ClearDashboardPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(filters.Filter) error); ok {
		r0 = rf(filterReq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DashboardPermissionsApi_ClearDashboardPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearDashboardPermissions'
type DashboardPermissionsApi_ClearDashboardPermissions_Call struct {
	*mock.Call
}

// ClearDashboardPermissions is a helper method to define mock.On call
//   - filterReq filters.Filter
func (_e *DashboardPermissionsApi_Expecter) ClearDashboardPermissions(filterReq interface{}) *DashboardPermissionsApi_ClearDashboardPermissions_Call {
	return &DashboardPermissionsApi_ClearDashboardPermissions_Call{Call: _e.mock.On("ClearDashboardPermissions", filterReq)}
}

func (_c *DashboardPermissionsApi_ClearDashboardPermissions_Call) Run(run func(filterReq filters.Filter)) *DashboardPermissionsApi_ClearDashboardPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(filters.Filter))
	})
	return _c
}

func (_c *DashboardPermissionsApi_ClearDashboardPermissions_Call) Return(_a0 error) *DashboardPermissionsApi_ClearDashboardPermissions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DashboardPermissionsApi_ClearDashboardPermissions_Call) RunAndReturn(run func(filters.Filter) error) *DashboardPermissionsApi_ClearDashboardPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadDashboardPermissions provides a mock function with given fields: filterReq
func (_m *DashboardPermissionsApi) DownloadDashboardPermissions(filterReq filters.Filter) ([]string, error) {
	ret := _m.Called(filterReq)

	if len(ret) == 0 {
		panic("no return value specified for DownloadDashboardPermissions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(filters.Filter) ([]string, error)); ok {
		return rf(filterReq)
	}
	if rf, ok := ret.Get(0).(func(filters.Filter) []string); ok {
		r0 = rf(filterReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(filters.Filter) error); ok {
		r1 = rf(filterReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardPermissionsApi_DownloadDashboardPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadDashboardPermissions'
type DashboardPermissionsApi_DownloadDashboardPermissions_Call struct {
	*mock.Call
}

// DownloadDashboardPermissions is a helper method to define mock.On call
//   - filterReq filters.Filter
func (_e *DashboardPermissionsApi_Expecter) DownloadDashboardPermissions(filterReq interface{}) *DashboardPermissionsApi_DownloadDashboardPermissions_Call {
	return &DashboardPermissionsApi_DownloadDashboardPermissions_Call{Call: _e.mock.On("DownloadDashboardPermissions", filterReq)}
}

func (_c *DashboardPermissionsApi_DownloadDashboardPermissions_Call) Run(run func(filterReq filters.Filter)) *DashboardPermissionsApi_DownloadDashboardPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(filters.Filter))
	})
	return _c
}

func (_c *DashboardPermissionsApi_DownloadDashboardPermissions_Call) Return(_a0 []string, _a1 error) *DashboardPermissionsApi_DownloadDashboardPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardPermissionsApi_DownloadDashboardPermissions_Call) RunAndReturn(run func(filters.Filter) ([]string, error)) *DashboardPermissionsApi_DownloadDashboardPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListDashboardPermissions provides a mock function with given fields: filterReq
func (_m *DashboardPermissionsApi) ListDashboardPermissions(filterReq filters.Filter) ([]service.DashboardAndPermissions, error) {
	ret := _m.Called(filterReq)

	if len(ret) == 0 {
		panic("no return value specified for ListDashboardPermissions")
	}

	var r0 []service.DashboardAndPermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(filters.Filter) ([]service.DashboardAndPermissions, error)); ok {
		return rf(filterReq)
	}
	if rf, ok := ret.Get(0).(func(filters.Filter) []service.DashboardAndPermissions); ok {
		r0 = rf(filterReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.DashboardAndPermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(filters.Filter) error); ok {
		r1 = rf(filterReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardPermissionsApi_ListDashboardPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDashboardPermissions'
type DashboardPermissionsApi_ListDashboardPermissions_Call struct {
	*mock.Call
}

// ListDashboardPermissions is a helper method to define mock.On call
//   - filterReq filters.Filter
func (_e *DashboardPermissionsApi_Expecter) ListDashboardPermissions(filterReq interface{}) *DashboardPermissionsApi_ListDashboardPermissions_Call {
	return &DashboardPermissionsApi_ListDashboardPermissions_Call{Call: _e.mock.On("ListDashboardPermissions", filterReq)}
}

func (_c *DashboardPermissionsApi_ListDashboardPermissions_Call) Run(run func(filterReq filters.Filter)) *DashboardPermissionsApi_ListDashboardPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(filters.Filter))
	})
	return _c
}

func (_c *DashboardPermissionsApi_ListDashboardPermissions_Call) Return(_a0 []service.DashboardAndPermissions, _a1 error) *DashboardPermissionsApi_ListDashboardPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardPermissionsApi_ListDashboardPermissions_Call) RunAndReturn(run func(filters.Filter) ([]service.DashboardAndPermissions, error)) *DashboardPermissionsApi_ListDashboardPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// UploadDashboardPermissions provides a mock function with given fields: filterReq
func (_m *DashboardPermissionsApi) UploadDashboardPermissions(filterReq filters.Filter) ([]string, error) {
	ret := _m.Called(filterReq)

	if len(ret) == 0 {
		panic("no return value specified for UploadDashboardPermissions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(filters.Filter) ([]string, error)); ok {
		return rf(filterReq)
	}
	if rf, ok := ret.Get(0).(func(filters.Filter) []string); ok {
		r0 = rf(filterReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(filters.Filter) error); ok {
		r1 = rf(filterReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardPermissionsApi_UploadDashboardPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadDashboardPermissions'
type DashboardPermissionsApi_UploadDashboardPermissions_Call struct {
	*mock.Call
}

// UploadDashboardPermissions is a helper method to define mock.On call
//   - filterReq filters.Filter
func (_e *DashboardPermissionsApi_Expecter) UploadDashboardPermissions(filterReq interface{}) *DashboardPermissionsApi_UploadDashboardPermissions_Call {
	return &DashboardPermissionsApi_UploadDashboardPermissions_Call{Call: _e.mock.On("UploadDashboardPermissions", filterReq)}
}

func (_c *DashboardPermissionsApi_UploadDashboardPermissions_Call) Run(run func(filterReq filters.Filter)) *DashboardPermissionsApi_UploadDashboardPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(filters.Filter))
	})
	return _c
}

func (_c *DashboardPermissionsApi_UploadDashboardPermissions_Call) Return(_a0 []string, _a1 error) *DashboardPermissionsApi_UploadDashboardPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardPermissionsApi_UploadDashboardPermissions_Call) RunAndReturn(run func(filters.Filter) ([]string, error)) *DashboardPermissionsApi_UploadDashboardPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// NewDashboardPermissionsApi creates a new instance of DashboardPermissionsApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardPermissionsApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardPermissionsApi {
	mock := &DashboardPermissionsApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
