// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/esnet/gdg/internal/service/filters"
	"github.com/esnet/gdg/internal/types"
	"github.com/grafana/grafana-openapi-client-go/models"
	mock "github.com/stretchr/testify/mock"
)

// NewFoldersApi creates a new instance of FoldersApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFoldersApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *FoldersApi {
	mock := &FoldersApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FoldersApi is an autogenerated mock type for the FoldersApi type
type FoldersApi struct {
	mock.Mock
}

type FoldersApi_Expecter struct {
	mock *mock.Mock
}

func (_m *FoldersApi) EXPECT() *FoldersApi_Expecter {
	return &FoldersApi_Expecter{mock: &_m.Mock}
}

// DeleteAllFolders provides a mock function for the type FoldersApi
func (_mock *FoldersApi) DeleteAllFolders(filter filters.V2Filter) []string {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllFolders")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(filters.V2Filter) []string); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// FoldersApi_DeleteAllFolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllFolders'
type FoldersApi_DeleteAllFolders_Call struct {
	*mock.Call
}

// DeleteAllFolders is a helper method to define mock.On call
//   - filter filters.V2Filter
func (_e *FoldersApi_Expecter) DeleteAllFolders(filter interface{}) *FoldersApi_DeleteAllFolders_Call {
	return &FoldersApi_DeleteAllFolders_Call{Call: _e.mock.On("DeleteAllFolders", filter)}
}

func (_c *FoldersApi_DeleteAllFolders_Call) Run(run func(filter filters.V2Filter)) *FoldersApi_DeleteAllFolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 filters.V2Filter
		if args[0] != nil {
			arg0 = args[0].(filters.V2Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FoldersApi_DeleteAllFolders_Call) Return(strings []string) *FoldersApi_DeleteAllFolders_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *FoldersApi_DeleteAllFolders_Call) RunAndReturn(run func(filter filters.V2Filter) []string) *FoldersApi_DeleteAllFolders_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadFolderPermissions provides a mock function for the type FoldersApi
func (_mock *FoldersApi) DownloadFolderPermissions(filter filters.V2Filter) []string {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFolderPermissions")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(filters.V2Filter) []string); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// FoldersApi_DownloadFolderPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFolderPermissions'
type FoldersApi_DownloadFolderPermissions_Call struct {
	*mock.Call
}

// DownloadFolderPermissions is a helper method to define mock.On call
//   - filter filters.V2Filter
func (_e *FoldersApi_Expecter) DownloadFolderPermissions(filter interface{}) *FoldersApi_DownloadFolderPermissions_Call {
	return &FoldersApi_DownloadFolderPermissions_Call{Call: _e.mock.On("DownloadFolderPermissions", filter)}
}

func (_c *FoldersApi_DownloadFolderPermissions_Call) Run(run func(filter filters.V2Filter)) *FoldersApi_DownloadFolderPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 filters.V2Filter
		if args[0] != nil {
			arg0 = args[0].(filters.V2Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FoldersApi_DownloadFolderPermissions_Call) Return(strings []string) *FoldersApi_DownloadFolderPermissions_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *FoldersApi_DownloadFolderPermissions_Call) RunAndReturn(run func(filter filters.V2Filter) []string) *FoldersApi_DownloadFolderPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadFolders provides a mock function for the type FoldersApi
func (_mock *FoldersApi) DownloadFolders(filter filters.V2Filter) []string {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFolders")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(filters.V2Filter) []string); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// FoldersApi_DownloadFolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFolders'
type FoldersApi_DownloadFolders_Call struct {
	*mock.Call
}

// DownloadFolders is a helper method to define mock.On call
//   - filter filters.V2Filter
func (_e *FoldersApi_Expecter) DownloadFolders(filter interface{}) *FoldersApi_DownloadFolders_Call {
	return &FoldersApi_DownloadFolders_Call{Call: _e.mock.On("DownloadFolders", filter)}
}

func (_c *FoldersApi_DownloadFolders_Call) Run(run func(filter filters.V2Filter)) *FoldersApi_DownloadFolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 filters.V2Filter
		if args[0] != nil {
			arg0 = args[0].(filters.V2Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FoldersApi_DownloadFolders_Call) Return(strings []string) *FoldersApi_DownloadFolders_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *FoldersApi_DownloadFolders_Call) RunAndReturn(run func(filter filters.V2Filter) []string) *FoldersApi_DownloadFolders_Call {
	_c.Call.Return(run)
	return _c
}

// ListFolderPermissions provides a mock function for the type FoldersApi
func (_mock *FoldersApi) ListFolderPermissions(filter filters.V2Filter) map[*types.NestedHit][]*models.DashboardACLInfoDTO {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListFolderPermissions")
	}

	var r0 map[*types.NestedHit][]*models.DashboardACLInfoDTO
	if returnFunc, ok := ret.Get(0).(func(filters.V2Filter) map[*types.NestedHit][]*models.DashboardACLInfoDTO); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[*types.NestedHit][]*models.DashboardACLInfoDTO)
		}
	}
	return r0
}

// FoldersApi_ListFolderPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFolderPermissions'
type FoldersApi_ListFolderPermissions_Call struct {
	*mock.Call
}

// ListFolderPermissions is a helper method to define mock.On call
//   - filter filters.V2Filter
func (_e *FoldersApi_Expecter) ListFolderPermissions(filter interface{}) *FoldersApi_ListFolderPermissions_Call {
	return &FoldersApi_ListFolderPermissions_Call{Call: _e.mock.On("ListFolderPermissions", filter)}
}

func (_c *FoldersApi_ListFolderPermissions_Call) Run(run func(filter filters.V2Filter)) *FoldersApi_ListFolderPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 filters.V2Filter
		if args[0] != nil {
			arg0 = args[0].(filters.V2Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FoldersApi_ListFolderPermissions_Call) Return(nestedHitToDashboardACLInfoDTOs map[*types.NestedHit][]*models.DashboardACLInfoDTO) *FoldersApi_ListFolderPermissions_Call {
	_c.Call.Return(nestedHitToDashboardACLInfoDTOs)
	return _c
}

func (_c *FoldersApi_ListFolderPermissions_Call) RunAndReturn(run func(filter filters.V2Filter) map[*types.NestedHit][]*models.DashboardACLInfoDTO) *FoldersApi_ListFolderPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListFolders provides a mock function for the type FoldersApi
func (_mock *FoldersApi) ListFolders(filter filters.V2Filter) []*types.NestedHit {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListFolders")
	}

	var r0 []*types.NestedHit
	if returnFunc, ok := ret.Get(0).(func(filters.V2Filter) []*types.NestedHit); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.NestedHit)
		}
	}
	return r0
}

// FoldersApi_ListFolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFolders'
type FoldersApi_ListFolders_Call struct {
	*mock.Call
}

// ListFolders is a helper method to define mock.On call
//   - filter filters.V2Filter
func (_e *FoldersApi_Expecter) ListFolders(filter interface{}) *FoldersApi_ListFolders_Call {
	return &FoldersApi_ListFolders_Call{Call: _e.mock.On("ListFolders", filter)}
}

func (_c *FoldersApi_ListFolders_Call) Run(run func(filter filters.V2Filter)) *FoldersApi_ListFolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 filters.V2Filter
		if args[0] != nil {
			arg0 = args[0].(filters.V2Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FoldersApi_ListFolders_Call) Return(nestedHits []*types.NestedHit) *FoldersApi_ListFolders_Call {
	_c.Call.Return(nestedHits)
	return _c
}

func (_c *FoldersApi_ListFolders_Call) RunAndReturn(run func(filter filters.V2Filter) []*types.NestedHit) *FoldersApi_ListFolders_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFolderPermissions provides a mock function for the type FoldersApi
func (_mock *FoldersApi) UploadFolderPermissions(filter filters.V2Filter) []string {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for UploadFolderPermissions")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(filters.V2Filter) []string); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// FoldersApi_UploadFolderPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFolderPermissions'
type FoldersApi_UploadFolderPermissions_Call struct {
	*mock.Call
}

// UploadFolderPermissions is a helper method to define mock.On call
//   - filter filters.V2Filter
func (_e *FoldersApi_Expecter) UploadFolderPermissions(filter interface{}) *FoldersApi_UploadFolderPermissions_Call {
	return &FoldersApi_UploadFolderPermissions_Call{Call: _e.mock.On("UploadFolderPermissions", filter)}
}

func (_c *FoldersApi_UploadFolderPermissions_Call) Run(run func(filter filters.V2Filter)) *FoldersApi_UploadFolderPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 filters.V2Filter
		if args[0] != nil {
			arg0 = args[0].(filters.V2Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FoldersApi_UploadFolderPermissions_Call) Return(strings []string) *FoldersApi_UploadFolderPermissions_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *FoldersApi_UploadFolderPermissions_Call) RunAndReturn(run func(filter filters.V2Filter) []string) *FoldersApi_UploadFolderPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFolders provides a mock function for the type FoldersApi
func (_mock *FoldersApi) UploadFolders(filter filters.V2Filter) []string {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for UploadFolders")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(filters.V2Filter) []string); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// FoldersApi_UploadFolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFolders'
type FoldersApi_UploadFolders_Call struct {
	*mock.Call
}

// UploadFolders is a helper method to define mock.On call
//   - filter filters.V2Filter
func (_e *FoldersApi_Expecter) UploadFolders(filter interface{}) *FoldersApi_UploadFolders_Call {
	return &FoldersApi_UploadFolders_Call{Call: _e.mock.On("UploadFolders", filter)}
}

func (_c *FoldersApi_UploadFolders_Call) Run(run func(filter filters.V2Filter)) *FoldersApi_UploadFolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 filters.V2Filter
		if args[0] != nil {
			arg0 = args[0].(filters.V2Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FoldersApi_UploadFolders_Call) Return(strings []string) *FoldersApi_UploadFolders_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *FoldersApi_UploadFolders_Call) RunAndReturn(run func(filter filters.V2Filter) []string) *FoldersApi_UploadFolders_Call {
	_c.Call.Return(run)
	return _c
}
