entities:
  dashboards:
    - template_name: template_example
      output:
        - folder: "General"
          org_id: 2
          dashboard_name: "Testing Foobar"
          template_data:
            Title: Bob Loves Candy
            enabledlight: true
            lightsources:
              - sun
              - moon
              - lightbulb
              - office lights
        - folder: "Testing"
          org_id: 3
          dashboard_name: ""
          template_data:
            Title: Uncle McDonalds
            enabledlight: true
            lightsources:
              - sun
              - moon