// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewExtendedApi creates a new instance of ExtendedApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExtendedApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExtendedApi {
	mock := &ExtendedApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExtendedApi is an autogenerated mock type for the ExtendedApi type
type ExtendedApi struct {
	mock.Mock
}

type ExtendedApi_Expecter struct {
	mock *mock.Mock
}

func (_m *ExtendedApi) EXPECT() *ExtendedApi_Expecter {
	return &ExtendedApi_Expecter{mock: &_m.Mock}
}

// GetConfiguredOrgId provides a mock function for the type ExtendedApi
func (_mock *ExtendedApi) GetConfiguredOrgId(orgName string) (int64, error) {
	ret := _mock.Called(orgName)

	if len(ret) == 0 {
		panic("no return value specified for GetConfiguredOrgId")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(orgName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(orgName)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(orgName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExtendedApi_GetConfiguredOrgId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfiguredOrgId'
type ExtendedApi_GetConfiguredOrgId_Call struct {
	*mock.Call
}

// GetConfiguredOrgId is a helper method to define mock.On call
//   - orgName string
func (_e *ExtendedApi_Expecter) GetConfiguredOrgId(orgName interface{}) *ExtendedApi_GetConfiguredOrgId_Call {
	return &ExtendedApi_GetConfiguredOrgId_Call{Call: _e.mock.On("GetConfiguredOrgId", orgName)}
}

func (_c *ExtendedApi_GetConfiguredOrgId_Call) Run(run func(orgName string)) *ExtendedApi_GetConfiguredOrgId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExtendedApi_GetConfiguredOrgId_Call) Return(n int64, err error) *ExtendedApi_GetConfiguredOrgId_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ExtendedApi_GetConfiguredOrgId_Call) RunAndReturn(run func(orgName string) (int64, error)) *ExtendedApi_GetConfiguredOrgId_Call {
	_c.Call.Return(run)
	return _c
}
