// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"reflect"

	"github.com/esnet/gdg/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewV2Filter creates a new instance of V2Filter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV2Filter(t interface {
	mock.TestingT
	Cleanup(func())
}) *V2Filter {
	mock := &V2Filter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V2Filter is an autogenerated mock type for the V2Filter type
type V2Filter struct {
	mock.Mock
}

type V2Filter_Expecter struct {
	mock *mock.Mock
}

func (_m *V2Filter) EXPECT() *V2Filter_Expecter {
	return &V2Filter_Expecter{mock: &_m.Mock}
}

// AddValidation provides a mock function for the type V2Filter
func (_mock *V2Filter) AddValidation(f domain.FilterType, validation domain.InputValidation, expected any) {
	_mock.Called(f, validation, expected)
	return
}

// V2Filter_AddValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddValidation'
type V2Filter_AddValidation_Call struct {
	*mock.Call
}

// AddValidation is a helper method to define mock.On call
//   - f filters.FilterType
//   - validation filters.InputValidation
//   - expected any
func (_e *V2Filter_Expecter) AddValidation(f interface{}, validation interface{}, expected interface{}) *V2Filter_AddValidation_Call {
	return &V2Filter_AddValidation_Call{Call: _e.mock.On("AddValidation", f, validation, expected)}
}

func (_c *V2Filter_AddValidation_Call) Run(run func(f domain.FilterType, validation domain.InputValidation, expected any)) *V2Filter_AddValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FilterType
		if args[0] != nil {
			arg0 = args[0].(domain.FilterType)
		}
		var arg1 domain.InputValidation
		if args[1] != nil {
			arg1 = args[1].(domain.InputValidation)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *V2Filter_AddValidation_Call) Return() *V2Filter_AddValidation_Call {
	_c.Call.Return()
	return _c
}

func (_c *V2Filter_AddValidation_Call) RunAndReturn(run func(f domain.FilterType, validation domain.InputValidation, expected any)) *V2Filter_AddValidation_Call {
	_c.Run(run)
	return _c
}

// GetExpectedString provides a mock function for the type V2Filter
func (_mock *V2Filter) GetExpectedString(filterType domain.FilterType) string {
	ret := _mock.Called(filterType)

	if len(ret) == 0 {
		panic("no return value specified for GetExpectedString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(domain.FilterType) string); ok {
		r0 = returnFunc(filterType)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// V2Filter_GetExpectedString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpectedString'
type V2Filter_GetExpectedString_Call struct {
	*mock.Call
}

// GetExpectedString is a helper method to define mock.On call
//   - filterType filters.FilterType
func (_e *V2Filter_Expecter) GetExpectedString(filterType interface{}) *V2Filter_GetExpectedString_Call {
	return &V2Filter_GetExpectedString_Call{Call: _e.mock.On("GetExpectedString", filterType)}
}

func (_c *V2Filter_GetExpectedString_Call) Run(run func(filterType domain.FilterType)) *V2Filter_GetExpectedString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FilterType
		if args[0] != nil {
			arg0 = args[0].(domain.FilterType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *V2Filter_GetExpectedString_Call) Return(s string) *V2Filter_GetExpectedString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *V2Filter_GetExpectedString_Call) RunAndReturn(run func(filterType domain.FilterType) string) *V2Filter_GetExpectedString_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpectedStringSlice provides a mock function for the type V2Filter
func (_mock *V2Filter) GetExpectedStringSlice(filterType domain.FilterType) ([]string, error) {
	ret := _mock.Called(filterType)

	if len(ret) == 0 {
		panic("no return value specified for GetExpectedStringSlice")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.FilterType) ([]string, error)); ok {
		return returnFunc(filterType)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.FilterType) []string); ok {
		r0 = returnFunc(filterType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.FilterType) error); ok {
		r1 = returnFunc(filterType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// V2Filter_GetExpectedStringSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpectedStringSlice'
type V2Filter_GetExpectedStringSlice_Call struct {
	*mock.Call
}

// GetExpectedStringSlice is a helper method to define mock.On call
//   - filterType filters.FilterType
func (_e *V2Filter_Expecter) GetExpectedStringSlice(filterType interface{}) *V2Filter_GetExpectedStringSlice_Call {
	return &V2Filter_GetExpectedStringSlice_Call{Call: _e.mock.On("GetExpectedStringSlice", filterType)}
}

func (_c *V2Filter_GetExpectedStringSlice_Call) Run(run func(filterType domain.FilterType)) *V2Filter_GetExpectedStringSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FilterType
		if args[0] != nil {
			arg0 = args[0].(domain.FilterType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *V2Filter_GetExpectedStringSlice_Call) Return(strings []string, err error) *V2Filter_GetExpectedStringSlice_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *V2Filter_GetExpectedStringSlice_Call) RunAndReturn(run func(filterType domain.FilterType) ([]string, error)) *V2Filter_GetExpectedStringSlice_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpectedValue provides a mock function for the type V2Filter
func (_mock *V2Filter) GetExpectedValue(filterType domain.FilterType) any {
	ret := _mock.Called(filterType)

	if len(ret) == 0 {
		panic("no return value specified for GetExpectedValue")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(domain.FilterType) any); ok {
		r0 = returnFunc(filterType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// V2Filter_GetExpectedValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpectedValue'
type V2Filter_GetExpectedValue_Call struct {
	*mock.Call
}

// GetExpectedValue is a helper method to define mock.On call
//   - filterType filters.FilterType
func (_e *V2Filter_Expecter) GetExpectedValue(filterType interface{}) *V2Filter_GetExpectedValue_Call {
	return &V2Filter_GetExpectedValue_Call{Call: _e.mock.On("GetExpectedValue", filterType)}
}

func (_c *V2Filter_GetExpectedValue_Call) Run(run func(filterType domain.FilterType)) *V2Filter_GetExpectedValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FilterType
		if args[0] != nil {
			arg0 = args[0].(domain.FilterType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *V2Filter_GetExpectedValue_Call) Return(v any) *V2Filter_GetExpectedValue_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *V2Filter_GetExpectedValue_Call) RunAndReturn(run func(filterType domain.FilterType) any) *V2Filter_GetExpectedValue_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterDataProcessor provides a mock function for the type V2Filter
func (_mock *V2Filter) RegisterDataProcessor(entityType domain.FilterType, entity domain.ProcessorEntity) error {
	ret := _mock.Called(entityType, entity)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDataProcessor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.FilterType, domain.ProcessorEntity) error); ok {
		r0 = returnFunc(entityType, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V2Filter_RegisterDataProcessor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDataProcessor'
type V2Filter_RegisterDataProcessor_Call struct {
	*mock.Call
}

// RegisterDataProcessor is a helper method to define mock.On call
//   - entityType filters.FilterType
//   - entity filters.ProcessorEntity
func (_e *V2Filter_Expecter) RegisterDataProcessor(entityType interface{}, entity interface{}) *V2Filter_RegisterDataProcessor_Call {
	return &V2Filter_RegisterDataProcessor_Call{Call: _e.mock.On("RegisterDataProcessor", entityType, entity)}
}

func (_c *V2Filter_RegisterDataProcessor_Call) Run(run func(entityType domain.FilterType, entity domain.ProcessorEntity)) *V2Filter_RegisterDataProcessor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FilterType
		if args[0] != nil {
			arg0 = args[0].(domain.FilterType)
		}
		var arg1 domain.ProcessorEntity
		if args[1] != nil {
			arg1 = args[1].(domain.ProcessorEntity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *V2Filter_RegisterDataProcessor_Call) Return(err error) *V2Filter_RegisterDataProcessor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V2Filter_RegisterDataProcessor_Call) RunAndReturn(run func(entityType domain.FilterType, entity domain.ProcessorEntity) error) *V2Filter_RegisterDataProcessor_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterReader provides a mock function for the type V2Filter
func (_mock *V2Filter) RegisterReader(entityType reflect.Type, fn domain.FilterReader) error {
	ret := _mock.Called(entityType, fn)

	if len(ret) == 0 {
		panic("no return value specified for RegisterReader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(reflect.Type, domain.FilterReader) error); ok {
		r0 = returnFunc(entityType, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V2Filter_RegisterReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterReader'
type V2Filter_RegisterReader_Call struct {
	*mock.Call
}

// RegisterReader is a helper method to define mock.On call
//   - entityType reflect.Type
//   - fn filters.FilterReader
func (_e *V2Filter_Expecter) RegisterReader(entityType interface{}, fn interface{}) *V2Filter_RegisterReader_Call {
	return &V2Filter_RegisterReader_Call{Call: _e.mock.On("RegisterReader", entityType, fn)}
}

func (_c *V2Filter_RegisterReader_Call) Run(run func(entityType reflect.Type, fn domain.FilterReader)) *V2Filter_RegisterReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		var arg1 domain.FilterReader
		if args[1] != nil {
			arg1 = args[1].(domain.FilterReader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *V2Filter_RegisterReader_Call) Return(err error) *V2Filter_RegisterReader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V2Filter_RegisterReader_Call) RunAndReturn(run func(entityType reflect.Type, fn domain.FilterReader) error) *V2Filter_RegisterReader_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type V2Filter
func (_mock *V2Filter) Validate(filterType domain.FilterType, v any) bool {
	ret := _mock.Called(filterType, v)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(domain.FilterType, any) bool); ok {
		r0 = returnFunc(filterType, v)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// V2Filter_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type V2Filter_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - filterType filters.FilterType
//   - v any
func (_e *V2Filter_Expecter) Validate(filterType interface{}, v interface{}) *V2Filter_Validate_Call {
	return &V2Filter_Validate_Call{Call: _e.mock.On("Validate", filterType, v)}
}

func (_c *V2Filter_Validate_Call) Run(run func(filterType domain.FilterType, v any)) *V2Filter_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FilterType
		if args[0] != nil {
			arg0 = args[0].(domain.FilterType)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *V2Filter_Validate_Call) Return(b bool) *V2Filter_Validate_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *V2Filter_Validate_Call) RunAndReturn(run func(filterType domain.FilterType, v any) bool) *V2Filter_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAll provides a mock function for the type V2Filter
func (_mock *V2Filter) ValidateAll(v any) bool {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAll")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(any) bool); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// V2Filter_ValidateAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAll'
type V2Filter_ValidateAll_Call struct {
	*mock.Call
}

// ValidateAll is a helper method to define mock.On call
//   - v any
func (_e *V2Filter_Expecter) ValidateAll(v interface{}) *V2Filter_ValidateAll_Call {
	return &V2Filter_ValidateAll_Call{Call: _e.mock.On("ValidateAll", v)}
}

func (_c *V2Filter_ValidateAll_Call) Run(run func(v any)) *V2Filter_ValidateAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *V2Filter_ValidateAll_Call) Return(b bool) *V2Filter_ValidateAll_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *V2Filter_ValidateAll_Call) RunAndReturn(run func(v any) bool) *V2Filter_ValidateAll_Call {
	_c.Call.Return(run)
	return _c
}
