---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: CONFIG
- type: document
  path: exampleSite/config.toml
  label: Settings
- type: heading
  label: PAGES
- type: directory
  path: exampleSite/content
  label: Pages
  create: all
  match: "*"
  templates:
  - page
- type: heading
  label: DOCS PAGES
- type: directory
  path: exampleSite/content/docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - page
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.75.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.75.1
