// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/esnet/gdg/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewCipherEncoder creates a new instance of CipherEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCipherEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *CipherEncoder {
	mock := &CipherEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CipherEncoder is an autogenerated mock type for the CipherEncoder type
type CipherEncoder struct {
	mock.Mock
}

type CipherEncoder_Expecter struct {
	mock *mock.Mock
}

func (_m *CipherEncoder) EXPECT() *CipherEncoder_Expecter {
	return &CipherEncoder_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type CipherEncoder
func (_mock *CipherEncoder) Decode(resourceType domain.ResourceType, b []byte) ([]byte, error) {
	ret := _mock.Called(resourceType, b)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.ResourceType, []byte) ([]byte, error)); ok {
		return returnFunc(resourceType, b)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.ResourceType, []byte) []byte); ok {
		r0 = returnFunc(resourceType, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.ResourceType, []byte) error); ok {
		r1 = returnFunc(resourceType, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CipherEncoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type CipherEncoder_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - resourceType domain.ResourceType
//   - b []byte
func (_e *CipherEncoder_Expecter) Decode(resourceType interface{}, b interface{}) *CipherEncoder_Decode_Call {
	return &CipherEncoder_Decode_Call{Call: _e.mock.On("Decode", resourceType, b)}
}

func (_c *CipherEncoder_Decode_Call) Run(run func(resourceType domain.ResourceType, b []byte)) *CipherEncoder_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ResourceType
		if args[0] != nil {
			arg0 = args[0].(domain.ResourceType)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CipherEncoder_Decode_Call) Return(bytes []byte, err error) *CipherEncoder_Decode_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *CipherEncoder_Decode_Call) RunAndReturn(run func(resourceType domain.ResourceType, b []byte) ([]byte, error)) *CipherEncoder_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// DecodeValue provides a mock function for the type CipherEncoder
func (_mock *CipherEncoder) DecodeValue(b string) (string, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for DecodeValue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CipherEncoder_DecodeValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeValue'
type CipherEncoder_DecodeValue_Call struct {
	*mock.Call
}

// DecodeValue is a helper method to define mock.On call
//   - b string
func (_e *CipherEncoder_Expecter) DecodeValue(b interface{}) *CipherEncoder_DecodeValue_Call {
	return &CipherEncoder_DecodeValue_Call{Call: _e.mock.On("DecodeValue", b)}
}

func (_c *CipherEncoder_DecodeValue_Call) Run(run func(b string)) *CipherEncoder_DecodeValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CipherEncoder_DecodeValue_Call) Return(s string, err error) *CipherEncoder_DecodeValue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CipherEncoder_DecodeValue_Call) RunAndReturn(run func(b string) (string, error)) *CipherEncoder_DecodeValue_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type CipherEncoder
func (_mock *CipherEncoder) Encode(resourceType domain.ResourceType, b []byte) ([]byte, error) {
	ret := _mock.Called(resourceType, b)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.ResourceType, []byte) ([]byte, error)); ok {
		return returnFunc(resourceType, b)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.ResourceType, []byte) []byte); ok {
		r0 = returnFunc(resourceType, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.ResourceType, []byte) error); ok {
		r1 = returnFunc(resourceType, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CipherEncoder_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type CipherEncoder_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - resourceType domain.ResourceType
//   - b []byte
func (_e *CipherEncoder_Expecter) Encode(resourceType interface{}, b interface{}) *CipherEncoder_Encode_Call {
	return &CipherEncoder_Encode_Call{Call: _e.mock.On("Encode", resourceType, b)}
}

func (_c *CipherEncoder_Encode_Call) Run(run func(resourceType domain.ResourceType, b []byte)) *CipherEncoder_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ResourceType
		if args[0] != nil {
			arg0 = args[0].(domain.ResourceType)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CipherEncoder_Encode_Call) Return(bytes []byte, err error) *CipherEncoder_Encode_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *CipherEncoder_Encode_Call) RunAndReturn(run func(resourceType domain.ResourceType, b []byte) ([]byte, error)) *CipherEncoder_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// EncodeValue provides a mock function for the type CipherEncoder
func (_mock *CipherEncoder) EncodeValue(b string) (string, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for EncodeValue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CipherEncoder_EncodeValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeValue'
type CipherEncoder_EncodeValue_Call struct {
	*mock.Call
}

// EncodeValue is a helper method to define mock.On call
//   - b string
func (_e *CipherEncoder_Expecter) EncodeValue(b interface{}) *CipherEncoder_EncodeValue_Call {
	return &CipherEncoder_EncodeValue_Call{Call: _e.mock.On("EncodeValue", b)}
}

func (_c *CipherEncoder_EncodeValue_Call) Run(run func(b string)) *CipherEncoder_EncodeValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CipherEncoder_EncodeValue_Call) Return(s string, err error) *CipherEncoder_EncodeValue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CipherEncoder_EncodeValue_Call) RunAndReturn(run func(b string) (string, error)) *CipherEncoder_EncodeValue_Call {
	_c.Call.Return(run)
	return _c
}
