// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/esnet/gdg/internal/domain"
	"github.com/esnet/gdg/internal/ports/outbound"
	mock "github.com/stretchr/testify/mock"
)

// NewDashboardService creates a new instance of DashboardService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardService {
	mock := &DashboardService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DashboardService is an autogenerated mock type for the DashboardService type
type DashboardService struct {
	mock.Mock
}

type DashboardService_Expecter struct {
	mock *mock.Mock
}

func (_m *DashboardService) EXPECT() *DashboardService_Expecter {
	return &DashboardService_Expecter{mock: &_m.Mock}
}

// ClearDashboardPermissions provides a mock function for the type DashboardService
func (_mock *DashboardService) ClearDashboardPermissions(filterReq outbound.Filter) error {
	ret := _mock.Called(filterReq)

	if len(ret) == 0 {
		panic("no return value specified for ClearDashboardPermissions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) error); ok {
		r0 = returnFunc(filterReq)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DashboardService_ClearDashboardPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearDashboardPermissions'
type DashboardService_ClearDashboardPermissions_Call struct {
	*mock.Call
}

// ClearDashboardPermissions is a helper method to define mock.On call
//   - filterReq outbound.Filter
func (_e *DashboardService_Expecter) ClearDashboardPermissions(filterReq any) *DashboardService_ClearDashboardPermissions_Call {
	return &DashboardService_ClearDashboardPermissions_Call{Call: _e.mock.On("ClearDashboardPermissions", filterReq)}
}

func (_c *DashboardService_ClearDashboardPermissions_Call) Run(run func(filterReq outbound.Filter)) *DashboardService_ClearDashboardPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 outbound.Filter
		if args[0] != nil {
			arg0 = args[0].(outbound.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DashboardService_ClearDashboardPermissions_Call) Return(err error) *DashboardService_ClearDashboardPermissions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DashboardService_ClearDashboardPermissions_Call) RunAndReturn(run func(filterReq outbound.Filter) error) *DashboardService_ClearDashboardPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllDashboards provides a mock function for the type DashboardService
func (_mock *DashboardService) DeleteAllDashboards(filter outbound.Filter) []string {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllDashboards")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) []string); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// DashboardService_DeleteAllDashboards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllDashboards'
type DashboardService_DeleteAllDashboards_Call struct {
	*mock.Call
}

// DeleteAllDashboards is a helper method to define mock.On call
//   - filter outbound.Filter
func (_e *DashboardService_Expecter) DeleteAllDashboards(filter any) *DashboardService_DeleteAllDashboards_Call {
	return &DashboardService_DeleteAllDashboards_Call{Call: _e.mock.On("DeleteAllDashboards", filter)}
}

func (_c *DashboardService_DeleteAllDashboards_Call) Run(run func(filter outbound.Filter)) *DashboardService_DeleteAllDashboards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 outbound.Filter
		if args[0] != nil {
			arg0 = args[0].(outbound.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DashboardService_DeleteAllDashboards_Call) Return(strings []string) *DashboardService_DeleteAllDashboards_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *DashboardService_DeleteAllDashboards_Call) RunAndReturn(run func(filter outbound.Filter) []string) *DashboardService_DeleteAllDashboards_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadDashboardPermissions provides a mock function for the type DashboardService
func (_mock *DashboardService) DownloadDashboardPermissions(filterReq outbound.Filter) ([]string, error) {
	ret := _mock.Called(filterReq)

	if len(ret) == 0 {
		panic("no return value specified for DownloadDashboardPermissions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) ([]string, error)); ok {
		return returnFunc(filterReq)
	}
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) []string); ok {
		r0 = returnFunc(filterReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(outbound.Filter) error); ok {
		r1 = returnFunc(filterReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DashboardService_DownloadDashboardPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadDashboardPermissions'
type DashboardService_DownloadDashboardPermissions_Call struct {
	*mock.Call
}

// DownloadDashboardPermissions is a helper method to define mock.On call
//   - filterReq outbound.Filter
func (_e *DashboardService_Expecter) DownloadDashboardPermissions(filterReq any) *DashboardService_DownloadDashboardPermissions_Call {
	return &DashboardService_DownloadDashboardPermissions_Call{Call: _e.mock.On("DownloadDashboardPermissions", filterReq)}
}

func (_c *DashboardService_DownloadDashboardPermissions_Call) Run(run func(filterReq outbound.Filter)) *DashboardService_DownloadDashboardPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 outbound.Filter
		if args[0] != nil {
			arg0 = args[0].(outbound.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DashboardService_DownloadDashboardPermissions_Call) Return(strings []string, err error) *DashboardService_DownloadDashboardPermissions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *DashboardService_DownloadDashboardPermissions_Call) RunAndReturn(run func(filterReq outbound.Filter) ([]string, error)) *DashboardService_DownloadDashboardPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadDashboards provides a mock function for the type DashboardService
func (_mock *DashboardService) DownloadDashboards(filter outbound.Filter) []string {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for DownloadDashboards")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) []string); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// DashboardService_DownloadDashboards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadDashboards'
type DashboardService_DownloadDashboards_Call struct {
	*mock.Call
}

// DownloadDashboards is a helper method to define mock.On call
//   - filter outbound.Filter
func (_e *DashboardService_Expecter) DownloadDashboards(filter any) *DashboardService_DownloadDashboards_Call {
	return &DashboardService_DownloadDashboards_Call{Call: _e.mock.On("DownloadDashboards", filter)}
}

func (_c *DashboardService_DownloadDashboards_Call) Run(run func(filter outbound.Filter)) *DashboardService_DownloadDashboards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 outbound.Filter
		if args[0] != nil {
			arg0 = args[0].(outbound.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DashboardService_DownloadDashboards_Call) Return(strings []string) *DashboardService_DownloadDashboards_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *DashboardService_DownloadDashboards_Call) RunAndReturn(run func(filter outbound.Filter) []string) *DashboardService_DownloadDashboards_Call {
	_c.Call.Return(run)
	return _c
}

// ListDashboardPermissions provides a mock function for the type DashboardService
func (_mock *DashboardService) ListDashboardPermissions(filterReq outbound.Filter) ([]domain.DashboardAndPermissions, error) {
	ret := _mock.Called(filterReq)

	if len(ret) == 0 {
		panic("no return value specified for ListDashboardPermissions")
	}

	var r0 []domain.DashboardAndPermissions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) ([]domain.DashboardAndPermissions, error)); ok {
		return returnFunc(filterReq)
	}
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) []domain.DashboardAndPermissions); ok {
		r0 = returnFunc(filterReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DashboardAndPermissions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(outbound.Filter) error); ok {
		r1 = returnFunc(filterReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DashboardService_ListDashboardPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDashboardPermissions'
type DashboardService_ListDashboardPermissions_Call struct {
	*mock.Call
}

// ListDashboardPermissions is a helper method to define mock.On call
//   - filterReq outbound.Filter
func (_e *DashboardService_Expecter) ListDashboardPermissions(filterReq any) *DashboardService_ListDashboardPermissions_Call {
	return &DashboardService_ListDashboardPermissions_Call{Call: _e.mock.On("ListDashboardPermissions", filterReq)}
}

func (_c *DashboardService_ListDashboardPermissions_Call) Run(run func(filterReq outbound.Filter)) *DashboardService_ListDashboardPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 outbound.Filter
		if args[0] != nil {
			arg0 = args[0].(outbound.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DashboardService_ListDashboardPermissions_Call) Return(dashboardAndPermissionss []domain.DashboardAndPermissions, err error) *DashboardService_ListDashboardPermissions_Call {
	_c.Call.Return(dashboardAndPermissionss, err)
	return _c
}

func (_c *DashboardService_ListDashboardPermissions_Call) RunAndReturn(run func(filterReq outbound.Filter) ([]domain.DashboardAndPermissions, error)) *DashboardService_ListDashboardPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListDashboards provides a mock function for the type DashboardService
func (_mock *DashboardService) ListDashboards(filter outbound.Filter) []*domain.DashboardV2Gdg {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListDashboards")
	}

	var r0 []*domain.DashboardV2Gdg
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) []*domain.DashboardV2Gdg); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.DashboardV2Gdg)
		}
	}
	return r0
}

// DashboardService_ListDashboards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDashboards'
type DashboardService_ListDashboards_Call struct {
	*mock.Call
}

// ListDashboards is a helper method to define mock.On call
//   - filter outbound.Filter
func (_e *DashboardService_Expecter) ListDashboards(filter any) *DashboardService_ListDashboards_Call {
	return &DashboardService_ListDashboards_Call{Call: _e.mock.On("ListDashboards", filter)}
}

func (_c *DashboardService_ListDashboards_Call) Run(run func(filter outbound.Filter)) *DashboardService_ListDashboards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 outbound.Filter
		if args[0] != nil {
			arg0 = args[0].(outbound.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DashboardService_ListDashboards_Call) Return(dashboardV2Gdgs []*domain.DashboardV2Gdg) *DashboardService_ListDashboards_Call {
	_c.Call.Return(dashboardV2Gdgs)
	return _c
}

func (_c *DashboardService_ListDashboards_Call) RunAndReturn(run func(filter outbound.Filter) []*domain.DashboardV2Gdg) *DashboardService_ListDashboards_Call {
	_c.Call.Return(run)
	return _c
}

// UploadDashboardPermissions provides a mock function for the type DashboardService
func (_mock *DashboardService) UploadDashboardPermissions(filterReq outbound.Filter) ([]string, error) {
	ret := _mock.Called(filterReq)

	if len(ret) == 0 {
		panic("no return value specified for UploadDashboardPermissions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) ([]string, error)); ok {
		return returnFunc(filterReq)
	}
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) []string); ok {
		r0 = returnFunc(filterReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(outbound.Filter) error); ok {
		r1 = returnFunc(filterReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DashboardService_UploadDashboardPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadDashboardPermissions'
type DashboardService_UploadDashboardPermissions_Call struct {
	*mock.Call
}

// UploadDashboardPermissions is a helper method to define mock.On call
//   - filterReq outbound.Filter
func (_e *DashboardService_Expecter) UploadDashboardPermissions(filterReq any) *DashboardService_UploadDashboardPermissions_Call {
	return &DashboardService_UploadDashboardPermissions_Call{Call: _e.mock.On("UploadDashboardPermissions", filterReq)}
}

func (_c *DashboardService_UploadDashboardPermissions_Call) Run(run func(filterReq outbound.Filter)) *DashboardService_UploadDashboardPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 outbound.Filter
		if args[0] != nil {
			arg0 = args[0].(outbound.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DashboardService_UploadDashboardPermissions_Call) Return(strings []string, err error) *DashboardService_UploadDashboardPermissions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *DashboardService_UploadDashboardPermissions_Call) RunAndReturn(run func(filterReq outbound.Filter) ([]string, error)) *DashboardService_UploadDashboardPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// UploadDashboards provides a mock function for the type DashboardService
func (_mock *DashboardService) UploadDashboards(filterReq outbound.Filter) ([]string, error) {
	ret := _mock.Called(filterReq)

	if len(ret) == 0 {
		panic("no return value specified for UploadDashboards")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) ([]string, error)); ok {
		return returnFunc(filterReq)
	}
	if returnFunc, ok := ret.Get(0).(func(outbound.Filter) []string); ok {
		r0 = returnFunc(filterReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(outbound.Filter) error); ok {
		r1 = returnFunc(filterReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DashboardService_UploadDashboards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadDashboards'
type DashboardService_UploadDashboards_Call struct {
	*mock.Call
}

// UploadDashboards is a helper method to define mock.On call
//   - filterReq outbound.Filter
func (_e *DashboardService_Expecter) UploadDashboards(filterReq any) *DashboardService_UploadDashboards_Call {
	return &DashboardService_UploadDashboards_Call{Call: _e.mock.On("UploadDashboards", filterReq)}
}

func (_c *DashboardService_UploadDashboards_Call) Run(run func(filterReq outbound.Filter)) *DashboardService_UploadDashboards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 outbound.Filter
		if args[0] != nil {
			arg0 = args[0].(outbound.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DashboardService_UploadDashboards_Call) Return(strings []string, err error) *DashboardService_UploadDashboards_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *DashboardService_UploadDashboards_Call) RunAndReturn(run func(filterReq outbound.Filter) ([]string, error)) *DashboardService_UploadDashboards_Call {
	_c.Call.Return(run)
	return _c
}
