// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// FindAllFiles provides a mock function for the type Storage
func (_mock *Storage) FindAllFiles(folder string, fullPath bool) ([]string, error) {
	ret := _mock.Called(folder, fullPath)

	if len(ret) == 0 {
		panic("no return value specified for FindAllFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) ([]string, error)); ok {
		return returnFunc(folder, fullPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) []string); ok {
		r0 = returnFunc(folder, fullPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(folder, fullPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_FindAllFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllFiles'
type Storage_FindAllFiles_Call struct {
	*mock.Call
}

// FindAllFiles is a helper method to define mock.On call
//   - folder string
//   - fullPath bool
func (_e *Storage_Expecter) FindAllFiles(folder interface{}, fullPath interface{}) *Storage_FindAllFiles_Call {
	return &Storage_FindAllFiles_Call{Call: _e.mock.On("FindAllFiles", folder, fullPath)}
}

func (_c *Storage_FindAllFiles_Call) Run(run func(folder string, fullPath bool)) *Storage_FindAllFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_FindAllFiles_Call) Return(strings []string, err error) *Storage_FindAllFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Storage_FindAllFiles_Call) RunAndReturn(run func(folder string, fullPath bool) ([]string, error)) *Storage_FindAllFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrefix provides a mock function for the type Storage
func (_mock *Storage) GetPrefix() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPrefix")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Storage_GetPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrefix'
type Storage_GetPrefix_Call struct {
	*mock.Call
}

// GetPrefix is a helper method to define mock.On call
func (_e *Storage_Expecter) GetPrefix() *Storage_GetPrefix_Call {
	return &Storage_GetPrefix_Call{Call: _e.mock.On("GetPrefix")}
}

func (_c *Storage_GetPrefix_Call) Run(run func()) *Storage_GetPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_GetPrefix_Call) Return(s string) *Storage_GetPrefix_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Storage_GetPrefix_Call) RunAndReturn(run func() string) *Storage_GetPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type Storage
func (_mock *Storage) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Storage_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Storage_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Storage_Expecter) Name() *Storage_Name_Call {
	return &Storage_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Storage_Name_Call) Run(run func()) *Storage_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_Name_Call) Return(s string) *Storage_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Storage_Name_Call) RunAndReturn(run func() string) *Storage_Name_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type Storage
func (_mock *Storage) ReadFile(filename string) ([]byte, error) {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(filename)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type Storage_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - filename string
func (_e *Storage_Expecter) ReadFile(filename interface{}) *Storage_ReadFile_Call {
	return &Storage_ReadFile_Call{Call: _e.mock.On("ReadFile", filename)}
}

func (_c *Storage_ReadFile_Call) Run(run func(filename string)) *Storage_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Storage_ReadFile_Call) Return(bytes []byte, err error) *Storage_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Storage_ReadFile_Call) RunAndReturn(run func(filename string) ([]byte, error)) *Storage_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type Storage
func (_mock *Storage) WriteFile(filename string, data []byte) error {
	ret := _mock.Called(filename, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(filename, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type Storage_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - filename string
//   - data []byte
func (_e *Storage_Expecter) WriteFile(filename interface{}, data interface{}) *Storage_WriteFile_Call {
	return &Storage_WriteFile_Call{Call: _e.mock.On("WriteFile", filename, data)}
}

func (_c *Storage_WriteFile_Call) Run(run func(filename string, data []byte)) *Storage_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_WriteFile_Call) Return(err error) *Storage_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_WriteFile_Call) RunAndReturn(run func(filename string, data []byte) error) *Storage_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
