baseURL = "https://netsage-project.github.io/gdg/"
title = "Grafana Dash-n-Go"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
#theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
theme = "compose_hack"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]
