name: Code Scanners
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.23.4


permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read


jobs:
  code_scanning:
    strategy:
      matrix:
#       job_name: [security, vuln_check, lint]
        job_name: [security, lint]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
          cache: false
      - name: Install Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Installing Go Tools
        run: ./bin/task install_tools      
      - name: Running Scan
        run: ./bin/task ${{ matrix.job_name }}

