name: Code Scanners
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read


jobs:
  code_scanning:
    strategy:
      matrix:
#       job_name: [security, vuln_check, lint]
        job_name: [security, lint]
        go_version: [ 1.25.1]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Go
        uses: ./actions/setup_go
        with:
          go_version: "${{ matrix.go_version }}"
      - name: Running Scan
        run: ./bin/task ${{ matrix.job_name }}

