name: Publish Hugo Documentation On New Tag 
on:
  push:
#   branches: 
#     - master
    tags:
      - v*

jobs:
  deployHugoPages:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
       with:
         submodules: true
         fetch-depth: 0
     - name: Setup Hugo
       uses: peaceiris/actions-hugo@v2
       with:
         hugo-version: 'latest'
         extended: true
     - name: NPM Dependencies
       run: |
         cd website && npm install
     - name: NPM Dependencies
       run: npm install postcss postcss-cli autoprefixer
     - name: Build
       run: | 
         cd website && npm run build
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./website/public

