name: Publish Hugo Documentation
on:
  push:
    branches: 
      - master

jobs:
  deployHugoPages:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         submodules: true
         fetch-depth: 0
     - name: Setup Hugo
       uses: peaceiris/actions-hugo@v2
       with:
         hugo-version: 'latest'
         extended: true
     - name: NPM Dependencies
       run: |
         cd documentation && npm install
     - name: NPM Dependencies
       run: npm install postcss postcss-cli autoprefixer
     - name: Build
       run: hugo --destination public --baseURL https://software.es.net/gdg -s documentation
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./documentation/public

